### PR TITLE
size terms are now fairly complete

### PR DESCRIPTION
**Pull request by fscottfoti**
Size terms are added as a table in the tables directory with one helper function which has a unit test under defaults.  Size terms are now used in the workplace location and destination choice models.  The destination choice models no longer use sampling, so are fairly close to final models.

### CODE REVIEW

**Comment by fscottfoti** [comment]
@jiffyclub This is passing on my laptop but is getting "killed" consistently by Travis.  Do you think it's something legitimate or just wait a bit and try again with Travis?

**Comment by jiffyclub** [comment]
The same thing is happening on UrbanSim, guess it's time to troubleshoot this.

**Comment by jiffyclub** [comment]
Based on this post it might be that we're using up all the memory: http://stackoverflow.com/questions/27564156/home-travis-build-sh-line-41-pid-killed-exit-code-137 Which I don't know there's anything we can do about that except try to use less memory for our tests.

**Comment by fscottfoti** [comment]
So 4gb is the limit?  Or is 3gb?

**Comment by jiffyclub** [comment]
I wish I knew. I asked in the Travis-CI IRC but no one responded. Trying Twitter.

**Comment by jiffyclub** [comment]
We may have to stop running simulations as part of the Travis runs unless we can think of a way to make the simulations use less memory.

**Comment by fscottfoti** [comment]
Running with fewer households seems like an option...

**Comment by fscottfoti** [comment]
I can try it and see if it fixes things

**Comment by jiffyclub** [comment]
It was always kind of mysterious as to why the UrbanSim runs stopped working because I don't think we changed anything in the sanfran_urbansim repo. Travis might have lowered the limit without warning.

**Comment by fscottfoti** [comment]
Seems to have fixed the tests by reducing memory use.  Now running with 50 households instead of 1000.

**Comment by jiffyclub** [comment]
That's great! Maybe we can do something similar in sanfran_urbansim?

**Comment by fscottfoti** [comment]
Should be able to.  But 50 records is hardly a test of the simulation - still, better than nothing.

**Pull request merged**
